### ISSUE TITLE
Improvement: add macro the get rid of using stringWithFormat:

### ISSUE THREAD

**Issue by albertschulz** [Smartling/ios-i18n#16]
I'd be really nice if there'd be a call like (as seen at mattts framework https://github.com/mattt/TTTLocalizedPluralString):
```
NSString *text = SLPluralizedString(@"%d apples", number, @"Comment");
```

instead of
```
int number = 42;
NSString *format = SLPluralizedString(@"%d apples", number, @"Comment");
NSString *text = [NSString stringWithFormat:format, number];
```

**Comment by HeEAaD** [comment]
+1

**Comment by jawalk4u** [comment]
![image](https://cloud.githubusercontent.com/assets/7856725/6765654/2bebb7b6-cffb-11e4-9298-6cb249826261.jpg)

**Comment by paiv** [comment]
@albertschulz, as in the mattt's, a macro could be a simple one like

    #define MyPluralizedStringFormat(key, n) \
        [NSString stringWithFormat:SLPluralizedString(key, n, nil), n]

My point why it is not in the library:

* It follows Apple's design of NSLocalizedString, which does no formatting.
* I want developers learn the concepts behind the library, and be conscious of why they are needed to switch from NSLocalizedString in their code, and what are the trade-offs. This is easy with two steps being separate: 1) query resources, 2) format string.
* Apple's implementation of plurals in .stringsdict is again different, and you need to understand that this library is not compatible and in what way.
* It is easy to add a custom macro tailored for your project needs.

**Comment by paiv** [comment]
@jawalk4u is it related to the question?
