### ISSUE TITLE
Base localizations files

### ISSUE THREAD

**Issue by torasike** [Smartling/ios-i18n#19]
Your lib does not look into base localization file. For example in iOS setting region is English, but I have only Base and French files.

**Comment by paiv** [comment]
@torasike hi, do you use `Base.lproj` for your strings?

> Base internationalization
> When using Base internationalization, Localizable.strings files should be in language-specific folders (like en.lproj), not in Base.lproj folder.

**Comment by torasike** [comment]
Yes.

**Comment by paiv** [comment]
@torasike, When using Base internationalization, Localizable.strings files should be in language-specific folders (like en.lproj), not in Base.lproj folder. -- Does this resolve your issue?

Also know that iOS7 has stringsdict with plurals support, which makes ios-i18n obsolete.

**Comment by torasike** [comment]
Yes, I get it. But, I guess i need investigate a bit and make more tests with that. thanks
