### ISSUE TITLE
Does not compile for armv7s arch (Xcode 7)

### ISSUE THREAD

**Issue by vilinskiy-playdayteam** [Smartling/ios-i18n#22]
Does not compile for armv7s arch (Xcode 7). Tested on iPhone 5c

**Comment by paiv** [comment]
@vilinskiy-playdayteam hi,
I don't see how `Does not compile for armv7s arch` gets fixed with removing `armv7s` from ARCHS, could you explain please? I suspect, you have compiled for armv7 in the end.
I don't have a 5C, so could not check this. On iPhone 5 master runs fine.

**Comment by vilinskiy-playdayteam** [comment]
Hi,

Yes, you are right. I ran project in Debug mode with Build Active Architecture Only flag set to YES. And default Xcode Architectures settings does not include armv7s acrhitecture (only armv7 and arm64). So, my project has been compiled for armv7, but i18n library has been compiled for armv7s.

Can it be more proper to switch to default Architecture settings (at least in Debug mode) for library, so other developers would not experience similar issues in their projects? I will highly appreciate this fix

**Comment by paiv** [comment]
I agree, and don't see a better solution for now. Can you update your pull request with changes only for Debug mode?

**Comment by a77ra** [comment]
> Does not compile for armv7s arch (Xcode 7). Tested on iPhone 5c
