### ISSUE TITLE
cannot import into swift project

### ISSUE THREAD

**Issue by jumpingfrog0** [Smartling/ios-i18n#24]
I import it into my swift project in `X-Bridging-Header.h`, but cannot build successfully
![image](https://cloud.githubusercontent.com/assets/7556575/10509725/46caf182-7361-11e5-9a33-8056925676f5.png)

What did I do wrong?

**Comment by paiv** [comment]
@jumpingfrog0 hi,
The library is not ready for Swift as-is, currently you need to link against `SmartlingLib` target; you have two options, either:
* embed source code into your project (`Smartling.i18n.xcodeproj` and `Smartling.i18n` folders), link against `SmartlingLib`
* or use [Carthage](https://github.com/Carthage/Carthage) -- it will generate `SmartlingLib.framework` for you

**Comment by jumpingfrog0** [comment]
@paiv Thanks. I try the first option, but swift don't support macros so that can't call functions such as `SLPluralizedString`. I wrote some generic functions with swift as same as the macros that you declare in `SLLocalization.h`, but it crash when I call those. I doubt I made some mistakes.
Finally, I use another libary: [TTTLocalizedPluralString](https://github.com/mattt/TTTLocalizedPluralString)
The library is also not ready for Swift, so I did the same thing as above and it worked fine.
Unfortunately, it only support `Int`.
I will try to make `Smartling.i18n` support to swift if I am free.

**Comment by paiv** [comment]
@jumpingfrog0 would you consider using [`.stringsdict`](https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html) format -- they have plurals, and Swift support out of the box?

**Comment by jumpingfrog0** [comment]
@paiv Thanks.Good idea.
